name = "StyledStrings"
uuid = "f489334b-da3d-4c2e-b8f0-e476e12c162b"
authors = ["TEC <git@tecosaur.net>"]
version = "1.0.0"

[deps]
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
TOML = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
